repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format
        types_or: [c++, c]
        args: [-i,'-style={IndentWidth: 4, ColumnLimit: 0, BreakStringLiterals: false, ReflowComments: false}']
        exclude: "Platform/Core/CMSIS/"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: "Platform/Core/CMSIS/"
      - id: end-of-file-fixer
        exclude: "Platform/Core/CMSIS/"
      - id: mixed-line-ending
        args: [--fix=crlf]
        exclude: "Platform/Core/CMSIS/"
      - id: check-added-large-files
